yedioapp/__init__.py
from flask import Flask
from yedioapp.config import config



def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config[config_name])
    app.config.from_pyfile('config.py')

    from yedioapp.main.views import main

    app.register_blueprint(main)

    return app

yedioapp/main/views.py
from flask import render_template, Blueprint, url_for

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/home.html')

@main.route('/services')
def services():
    return render_template('main/services.html')


@main.route('/about')
def about():
    return render_template('main/about.html')


@main.route('/contact')
def contact():
    return render_template('main/contact.html')

yedioapp/templates/includes/_nav.html
<!-- <header>
    <nav>
        <ul class="list-inline text-center mt-3">
            <li class="list-inline-item"><a href="{{url_for('main.home')}}">Acceuil</a></li>
            <li class="list-inline-item"><a href="{{url_for('main.services')}}">Services</a></li>
            <li class="list-inline-item"><a href="{{url_for('main.about')}}">About</a></li>
            <li class="list-inline-item"><a href="{{url_for('main.contact')}}">Contact</a></li>
        </ul>
    </nav>
</header> -->

<!-- <header>
   
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('main.home')}}">YeDio</a>
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{{url_for('main.home')}}">Acceuil</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('main.services')}}">Services</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('main.contact')}}">Contact</a></li>
            </ul>
        </div>
    </nav>
    
</header> -->

<!-- <header>
   
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('main.home')}}">YeDio</a>
            <button class="navbar-toggler"><span class="navbar-toggle-icon" data-toggle="collapse" data-target="#navbarNav"></span></button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="{{url_for('main.home')}}">Acceuil</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{url_for('main.services')}}">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{url_for('main.contact')}}">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header> -->

<div class="container">
    <ul class="nav nav-pills ml-auto justify-content-center pt-2 bg-light">
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.home')}}">Acceuil</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.services')}}">Services</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.contact')}}">Contact</a></li>
    </ul>
</div>

yedioapp/templates/layouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome.min.css')}}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% include 'includes/_nav.html' %}
    <div class="container text-center">
        {% block content %}

        {% endblock %}
    </div>

    <script src="{{url_for('static', filename='js/jquery-3.3.1.slim.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</body>
</html>

yedioapp/templates/main/about.html
{% extends 'layouts.html' %}

{% block content %}
    <h1 class="text-muted mb-2">About Us</h1>
    <p class="text-muted">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita iure nobis voluptatem sed, facere ut ipsam beatae consequuntur dolore laboriosam repellat minus quos perferendis nostrum. Placeat maiores deleniti perferendis aliquid.</p>

    <h2>Nos Domaines</h2>
    <div class="row">
        <div class="col-md-6 m-auto">
            <ul class="list-group mb-2">
                <li class="list-group-item">Climatisation</li>
                <li class="list-group-item">Electricité</li>
                <li class="list-group-item">Plomberie</li>
            </ul>
        </div>

        <div class="col-md-6 m-auto">
            <ul class="list-group mb-2">
                <a class="list-group-item list-group-item-action" href="#">Climatisation</a>
                <a class="list-group-item list-group-item-action" href="">Electricité</a>
                <a class="list-group-item list-group-item-action" href="">Plomberie</a>
            </ul> 
        </div>
    </div>
    

    
{% endblock %}

yedioapp/templates/main/contact.html
{% extends 'layouts.html' %}

{% block content %}
    <h1>Contact Us</h1>
{% endblock %}

yedioapp/templates/main/home.html
{% extends 'layouts.html' %}
{% block tittle %}Bienvenue | Yedio (Un autre regard){% endblock %}
{% block content %}

        <div class="row">
            <div class="col-sm m-auto justify-content-center">

                <div id="slider" class="carousel slide mb-5" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img width="100%" height="300px" class="d-block" src="{{url_for('static', filename='img/air.png')}}" alt="First slide">
                            <div class="carousel-caption">
                                <h1 class="text-muted text-center display-4">Bienvenue à YeDio</h1>
                                <div>
                                    <button class="btn btn-outline-info btn-sm">Contact us</button>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img width="100%" height="300px" class="d-block" src="{{url_for('static', filename='img/electric.jpg')}}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img width="100%" height="300px" class="d-block" src="{{url_for('static', filename='img/plumb.jpg')}}" alt="Third slide">
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

yedioapp/templates/main/services.html
{% extends 'layouts.html' %}

{% block title %}Yedio | Nos services{% endblock %}

{% block content %}

<h1 class="text-muted mb-4">Nos différents services</h1>

<div class="row">
    <div class="col-sm">
        <div class="border rounded">
            <h2 class="h2">Climatisation</h2>
            <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet nobis vitae perferendis, sapiente ratione.</p>
        </div>
    </div>

    <div class="col-sm">
        <div class="border rounded">
            <h2 class="h2">Climatisation</h2>
            <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet nobis vitae perferendis, sapiente ratione.</p>
        </div>
    </div>

    <div class="col-sm">
        <div class="border rounded">
            <h2 class="h2">Climatisation</h2>
            <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet nobis vitae perferendis, sapiente ratione.</p>
        </div>
    </div>
</div>

{% endblock %}